### ISSUE TITLE
Attribute Ranges

### ISSUE THREAD

**Issue by robme91** [robme91/se-ws-project#13]
Wir müssen uns auf ranges der Attribute einigen. Damit sowas in der dsl geprüft werden kann.
 
* levelTime ?
** ich denke in sekunden und von 0- 300 (5min) ?
* speed ?
** wird nur ganzzahlig in datei eingegeben, aber kann im generator als float dann gesetzt werden
** würde sagen 1 - 10 ?
* drinkSpeed ?
** 1-10?
* beerLevel ?
** 0 - 100 (wegen Prozent?)
* damage (von enemy)
** 0-100 (wegen Prozent?)
* ki
** sichtweite: 0-24 (Block Anzahl, quasi kann man dann 3 Blöcke weit gucken?)
** intelligenz: 0-100 (Prozent wegen Wahrscheinlichkeiten?)

**Comment by robme91** [comment]
wenn hier festgelegte werte festehen, dann kann das in den regelwerk issue übernommen werden.

**Comment by devfoo-one** [comment]
- `levelTime` = 0 - 600
  - entspricht den Sekunden
- `speed` = 0 - 100
  - Fantasiezahl, 0 bedeutet bewegt sich nicht
- `drinkSpeed` = 1 - 100
  - Prozent pro Sekunde
- `beerLevel` = 1 - 100
  - Prozent
- `damage` = 0 - 100
  - Prozent, die vom *ursprünglichen Wert* abgezogen werden
- ki
  - `sightDistance` = 0 - 24
    - entspricht Blöcken, also * 32 px
  - `intelligence` = 0 - 100
    - Prozent

**Comment by devfoo-one** [comment]
moved to wiki
