### ISSUE TITLE
Initial positions

### ISSUE THREAD

**Issue by robme91** [robme91/se-ws-project#43]
Für den level restart brauchen wir initial positions, damit alle characktere und der spieler an die ursprüngliche position zurück gesetzt werden.
aktuell funktioniert der restart so wie das resume, nur dass die zeit und bier wieder aufgefüllt werden

**Comment by devfoo-one** [comment]
Idee: LevelController im Constructor die AbstractLevel Klasse übergeben und ihn selbst die Instanz erzeugen lassen
