### ISSUE TITLE
Nächstes level auswählen

### ISSUE THREAD

**Issue by robme91** [robme91/se-ws-project#48]
Man könnte auch direkt beim winnign state noch fragen ob direkt das nächste level gestartet werden soll. 
Dann müsste in die gameutils eine map, die als key die class objects der levels bekommt (zuweisung in levelmenustate) und als value ob sie bereits gespielt wurden (boolean is played) . dann wird wenn der spieler im neü nächstes level spielen wählt einfach die map durchgegangen und das erste level, dass noch nicht gespielt wird, wird im playing state als current level gesetzt. und in der map das isplayed auf true. so dass iwann alle levels durchgespielt sind(reihenfolge egal, da keine schwieirgkeit und kein freischalten impl. ist).

Sind alle levels auf isplayed == true, dann kommt man ins level menu zurück oder es gibt ein hinweis. alle levels werden dann wieder auf isplayed false gesetzt.

**Comment by robme91** [comment]
bringt halt noch codezeilen

**Comment by robme91** [comment]
statt is played lieber isWon, damit levels die noch nicht gewonnen wurden gespielt werden.

**Comment by robme91** [comment]
is drin

**Comment by robme91** [comment]
warten auf pr merge

**Comment by devfoo-one** [comment]
#55
