### ISSUE TITLE
Position bei Hit setzen

### ISSUE THREAD

**Issue by robme91** [robme91/se-ws-project#5]
Wenn der Spieler oder ein NPC etwas hitted, dann wird aktuell die alte position beibehalten. Allerdings kommt es daruch bei höheren Geschwindigkeiten zu Positionen die weit entfernt vom gehitteten Objekt sind. Deshalb sollte der Naheste Schnittpunkt gewählt werden um den Spieler dorthin zu setzen.
Dafür könnte die GeomUtil Klasse und dessen intersects Methode verwendet werden.
Diese Eigenschaft ist zwar etwas blöd, aber nicht so hoch zu priorisieren.

**Comment by devfoo-one** [comment]
Das Problem is komplexer als ich dachte... 
- http://www.wildbunny.co.uk/blog/2011/12/14/how-to-make-a-2d-platform-game-part-2-collision-detection/
- http://higherorderfun.com/blog/2012/05/20/the-guide-to-implementing-2d-platformers/

**Comment by devfoo-one** [comment]
The solution presented in 0538406 has some performance issues but it should work for now.
