### ISSUE TITLE
Level Menu

### ISSUE THREAD

**Issue by robme91** [robme91/se-ws-project#9]
Das level Menü muss generischer werden.
Anhand von reflection müssen die level klassen als buttons erstellt werden evtl. mit preview images, so dass beim hineinkopieren eines levels, nicht jedesmal die level menu klasse angepasst werden musss.

**Comment by devfoo-one** [comment]
http://stackoverflow.com/questions/520328/can-you-find-all-classes-in-a-package-using-reflection

**Comment by robme91** [comment]
fertig
